version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5002:5002"
    networks:
      - hrms-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  # Host 3000 -> Container 80 (NGINX default)
    networks:
      - hrms-net

networks:
  hrms-net:
    driver: bridge
