version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5002:5002"
    volumes:
      - uploads-data:/app/uploads
    networks:
      - hrms-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  
    networks:
      - hrms-net

volumes:
  uploads-data:

networks:
  hrms-net:
    driver: bridge