version: '3.8'
services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5002:5002"
    networks:
      - hrms-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - hrms-net

networks:
  hrms-net:
    driver: bridge
