version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"
    networks:
      - app-net

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
