name: CI/CD Deployment to EC2 with Docker and ALB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync project files to EC2
      run: |
        rsync -avz --exclude 'node_modules' --exclude '.git' ./ ${{ secrets.HOST_SSH }}:${{ secrets.DEPLOY_PATH }}

    - name: SSH and Deploy with Cache
      run: |
        ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=5 -o StrictHostKeyChecking=no ${{ secrets.HOST_SSH }} << 'EOF'
          set -e
          cd ${{ secrets.DEPLOY_PATH }}

          echo "Building Docker images with cache..."
          docker-compose build

          echo "Restarting containers..."
          docker-compose up -d --remove-orphans

          echo "Deployment completed! ✅"
        EOF
